# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: leggers.me
email: lucas@leggers.me
description: > # this means to ignore newlines until "baseurl:"
  Lucas Eggers art gif animation vector graphic portfolio
url: "http://leggers.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: leggers
first_name: lucas
last_name: eggers
top_link:
  name: stuff
  path: stuff
middle_link:
  name: info
  path: info
bottom_link:
  name: other
  path: other

collections:
  vector_graphics:
    output: true
    moving: false

# Build settings
markdown: kramdown
theme: jekyll-sofie_portfolio
exclude:
  - Gemfile
  - Gemfile.lock
